services:
  db_tp_coord_front_back:
    container_name: db_tp_coord_front_back
    restart: unless-stopped
    image: postgres:latest
    environment:
      - ENGINE=postgresql,
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASS}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./dockerdata/postgres:/var/lib/postgresql/data
    ports:
      - 5440:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - course_tp_coord_front_back

  db_migration_tp_coord_front_back:
    container_name: db_migration_tp_coord_front_back
    build: ./backend
    command: >
      bash -c "flask db upgrade"
    env_file:
      - .env
    depends_on:
      db_tp_coord_front_back:
        condition: service_healthy
    networks:
      - course_tp_coord_front_back

  backend_tp_coord_front_back:
    build: ./backend
    container_name: backend_tp_coord_front_back
    restart: unless-stopped
    env_file: .env
    command: gunicorn --config gunicorn-cfg.py --reload run:app
    ports:
      - 5005:5005
    volumes:
      - ./backend/migrations:/code/migrations
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /code
        - action: rebuild
          path: ./backend/requirements.txt
        - action: rebuild
          path: ./.env
    depends_on:
      db_migration_tp_coord_front_back:
        condition: service_completed_successfully
    networks:
      - course_tp_coord_front_back

  hasura_tp_coord_front_back:
    container_name: hasura_tp_coord_front_back
    image: hasura/graphql-engine:v2.44.0
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      - HASURA_GRAPHQL_DATABASE_URL=postgresql://${DB_USERNAME}:${DB_PASS}@db_tp_coord_front_back:5432/${DB_NAME}
      - HASURA_GRAPHQL_ENABLE_CONSOLE=true
      - HASURA_GRAPHQL_DEV_MODE=true
      - HASURA_GRAPHQL_ADMIN_SECRET=${HASURA_GRAPHQL_ADMIN_SECRET}
      - HASURA_GRAPHQL_JWT_SECRET=${HASURA_GRAPHQL_JWT_SECRET}
      - HASURA_GRAPHQL_UNAUTHORIZED_ROLE=anonymous
    depends_on:
      db_tp_coord_front_back:
        condition: service_healthy
    networks:
      - course_tp_coord_front_back

  frontend_tp_coord_front_back:
    container_name: frontend_tp_coord_front_back
    restart: unless-stopped
    build: ./frontend
    ports:
      - 3000:3000
    depends_on:
      - backend_tp_coord_front_back
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
        - action: rebuild
          path: ./frontend/src/styles
        - action: rebuild
          path: ./frontend/package*.json
    networks:
      - course_tp_coord_front_back

networks:
  course_tp_coord_front_back:
    name: course_tp_coord_front_back
    driver: bridge
